[default]
flask_env = "development"
db_host = "localhost"
db_port = 5433
db_name = "booking_db"
db_user = "booking_user"
booking_api_base_url = "http://localhost:5001"
redis_host = "localhost"
redis_port = 6379
exchange_rate_api_base_url = "https://api.exchangerate-api.com/v4/latest"

[development]
db_host = "localhost"
booking_api_base_url = "http://localhost:5001"

[production]
db_host = "@format {this.env_db_host}"
booking_api_base_url = "@format {this.env_booking_api_url}"

[testing]
db_host = "localhost"
db_port = 5434
db_name = "test_booking_db"
db_user = "test_user"

[docker]
db_host = "postgres"
db_port = 5432
db_name = "booking_db"
db_user = "booking_user"
booking_api_base_url = "http://api_app:5001"
redis_host = "redis"
