"""create bookings table

Revision ID: 77252a642a80
Revises: 
Create Date: 2026-07-13 15:01:31.665831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77252a642a80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('conversion_key', sa.String(length=255), nullable=True),
    sa.Column('property_id', sa.String(length=64), nullable=True),
    sa.Column('referral_property_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('travel_purpose', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=True),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.Column('site_key', sa.String(length=16), nullable=True),
    sa.Column('device', sa.String(length=16), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
